# Generated by Django 4.2.7 on 2023-11-14 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('title', models.CharField(max_length=50, verbose_name='Вакансия')),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False)),
                ('company_title', models.CharField(max_length=20, verbose_name='Название компании')),
                ('company_descr', models.TextField(verbose_name='Описание компании')),
                ('salary', models.CharField(max_length=7, verbose_name='Зарплата')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('experience', models.CharField(max_length=20, verbose_name='Требуемый опыт')),
                ('responsibilities', models.TextField(verbose_name='Обязанности будущего сотрудника')),
                ('working_conditions', models.TextField(verbose_name='Условия')),
                ('applicants', models.ManyToManyField(blank=True, related_name='applied_vacancies_vacancies', to=settings.AUTH_USER_MODEL)),
                ('who_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to=settings.AUTH_USER_MODEL, verbose_name='Представитель компании')),
            ],
        ),
    ]
