# Generated by Django 4.2.7 on 2023-11-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='applied_vacancies',
            field=models.ManyToManyField(blank=True, related_name='applicants_resumes', to='vacancy.vacancy'),
        ),
    ]
